/* AUTHENTICATION */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";


export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* LIST */
export const LIST = "LIST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";

/* COURSE */
export const COURSE_POST = "COURSE_POST";
export const COURSE_POST_SUCCESS = "COURSE_POST_SUCCESS";
export const COURSE_POST_FAILURE = "COURSE_POST_FAILURE";

/* NOTE */
export const NOTE_POST = "NOTE_POST";
export const NOTE_POST_SUCCESS = "NOTE_SUCCESS";
export const NOTE_POST_FAILURE = "NOTE_FAILURE";

/* FEEDBACK */
export const FEEDBACK_POST = "FEEDBACK_POST";
export const FEEDBACK_POST_SUCCESS = "FEEDBACK_SUCCESS";
export const FEEDBACK_POST_FAILURE = "FEEDBACK_FAILURE";